version: '3'
services:
  server:
    image: serverimage
    container_name: servercontainer
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - 8080:8080
    command: python3 server.py
  client:
    image: clientimage
    container_name: clientcontainer
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    depends_on:
      - server
    network_mode: host
    command: python3 client.py
